using Spartaxx.BusinessObjects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Data;
using Spartaxx.BusinessObjects.Litigation;
using Spartaxx.BusinessObjects.GAHearingDetails;

namespace Spartaxx.DataAccess
{
    public interface IClientIndexRepository
    {
        PXTboListDefinition getListDefinitions(PXTboListDefinition objListDefinition);
        List<PTXboProject> getProjectDetails(int ClientId);
        PTXboClientDeliveryMethods getClientDeliveryMethods(int ClientId);
        DataTable getAccountDetailsCount(string ClientNumber);
        PTXboDashboardAccountCount getAccountDetailsCount_Dashboard(int ClientID);
        List<PTXboAccountDetails> getAccountsForBinding(PTXboGetAccountsForBinding model);
        List<PTXboMSPropertyConditionQuestionnaire> getMSPropertyCondition(PTXboPropertyConditionModel objmodel);
        //PTXboClientAndAccountDetails getClientAndAccountDetails(PTXboClientAndAccountDetails model);
        string getParamValue(int paramID);
        DataSet getClientNumber(string ClientNumber);
        DataSet getResultState(int ClientID);
        PTXboClientGroupContact getClientGroupContact(PTXboParameters model);
        List<PTXboMainScreenFieldNames> getMainScreenFieldName(PTXboParameters model);
        DataSet LoadDropDownForTermsFilter(int clienID);
        List<PTXboClientGiftcardHistory> getGiftCardSentDateHistory(int ClientID);
        List<PTXboClientTermsDetails> getClientTerms(PTXboClientTerms model);
        List<PTXboTermLevelHistory> getTermLevelHistory(int GroupId);
        List<PTXboClientGroupRecentPackageDetails> getClientGroupRecentPackageDetails(int clientId, int stateID, string County);
        List<PTXboClientPackageAccountDetails> GetClientPackageAccountDetails(int clientId, int stateID, string County, int packageTypeId, string packageTypeMode);
        List<PTXboClientContactLog> getClientContactLog(PTXboParameters model);
        DataTable getClientAndDeliveryMethod(string ClientNumber);
        List<PTXboCorrespondenceLogOld> GetOldCorrLog(string ClientNumber);
        DataSet getClientConsolidationClientDetails(string ClientNumber);
        DataSet getCAFHistory(int ClientId);
        List<PTXboTaxBillClientSearchResult> getTaxBillAuditClients(PTXboTaxBillClientSearchRequest objPTXboTaxBillClientSearch);
        DataSet getPTAXCAFHistory(string ClientNumber);
        List<PTXboAccountNotesProperty> GetAccountNotes(int accountId);
        List<PTXboHearingDetailsRemarks> GetHearingRemarks(PTXboParameters model);
        List<PTXboAofARemarks> getAofARemarks(int accountId);
        List<PTXboAgentRemarks> GetAgentRemarks(PTXboParameters model);
        List<PTXboPropertyRemarks> GetPropertyRemarks(int accountId);
        List<BusinessObjects.ViewModels.PTXMainScreenInvoiceDetailResult> getInvoicecollectionDetails(PTXboParameters model);
        List<PTXboInvoiceAdjustmentRequestDetails> GetInvoiceAdjRequestDetails(int Invoiceid);
        List<PTXboCCPayment> GetCCPaymentDetails(int ClientID);
        List<PTXboInvoiceAdjustmentDetails> GetInvoiceAdjustmentAuditDetails(int Invoiceid); 
        List<PTXboInvoiceExemptionJurisdictionHistory> GetInvoiceExemptionJurisdictionHistory(PTXboParameters model);
        List<PTXboCSPaymentPlanDetails> getClientPaymentPlan(string invoiceIdList);
        List<PTXboCSSettlementPlanDetails> getClientSettlementPlan(string invoiceIdList);
        List<PTXboCSPaymentPlanDetails> getClientPaymentPlanHistory(int invoiceId);
        List<PTXboCSSettlementPlanDetails> getClientSettlementPlanHistory(int invoiceId);
        List<PTXboFinancials> getFinancialDetails(int Accountid);
        DataSet GetDNDFlagStatus(PTXboParameters model);
        string GetAccountDetailFlags(PTXboParameters model);
        PTXboAccountSetupParameters getAccountSetupParameterDetails(int AccountID);
        PTXboPropertyDetails getPropertyDetailsData(PTXboParameters model);
        bool GetMainscreenGotoDDLValues(PTXboMainScreenFieldNames requestInput, out List<PTXboMainScreenFieldNames> getGotoDDLVal, out string errorMessage);
        PTXboValueNotice getValueNoticeData(PTXboParameters model);
        List<PTXboHearingDetails> getHearingDetailsData(PTXboParameters model);
        List<PTXboHearingResults> getHearingResultData(PTXboParameters model);
        double getPriorYearTaxRateForSelectedAccount(PTXboParameters modelrate);
        List<DataObjects.PTXdoAccountJurisdiction> getAccountJurisdiction(PTXboParameters modelrate);
        List<DataObjects.PTXdoAccountJurisdiction> getAccountTaxRollJurisdiction(PTXboParameters modelrate);
        List<PTXboCountyJurisdiction> getCountyJurisdiction(PTXboParameters modelrate);
        PTXboFCIPropertyDetails getFCIPropertyDetails(PTXboFCIPropertyDetails propertyDetails);
        List<PTXboFCIDataRemarks> GetFCIDataRemarksDetails(int PropertyDetailsId);
        bool getmenuIsActivebasedOnUserRole(PTXbomenuIsActivebasedOnUserRole model);
        List<PTXboACCLlogSearchResult> getACCLlogDetails(PTXboACCLlogSearchRequest objACCLlogSearchRequest);
        DataSet getACCLlogDetailsNew(PTXboACCLlogSearchRequest objACCLlogSearchRequest);
        int MainScreenupdateClientCodes(PTXboInsertUpdateClientCode model);
        string generateTemporaryClientNumber(string TaxYear);
        DataSet CheckClientDetailsBeforeGeneration(int ClientId);
        bool updateClientDeliveryMethods(PTXboClientDeliveryMethods objClientDeliveryMethods);
        List<PTXboCAFRequestonExpiry> getCAFRequestonExpiry(PTXboParameters model);
        bool updateGroupDetails(PTXboGroup objGroupDetails);
        List<PTXboAccountLevelHistory> getTermAccountLevelHistory(int GroupId);
        PTXboGroup getTermsDetails(int GroupId);
        DataTable getAssandUnAssAccountscount(PTXboSearchAccountCriteria objSearchAccountCriteria);
        List<PTXboAgreements> getAgreementsHistory(int GroupId);
        List<PTXboTermAccounts> getTermsAccounts(PTXboSearchAccountCriteria objSearchAccountCriteria);
        List<PTXboTermsDetails> getAccountTermHistory(int AccountId);
        List<PTXboTermsDetails> getAccountCurrentTermDetails(int AccountId);
        PTXboAgreements getAgreementDetails(int GroupID);
        DataTable getCafAccountCountbasedonStatus(int clientID);
        PTXboHearingDetailsProperty GetHearingDetails(PTXboParameters model);
        DataSet loadInformalInformalFlag(PTXboParameters model);
        List<PTXboHearingDateHistory> GetHearingDateHistory(int HearingDetailsId);
        List<PTXboCMAccountLetterDetails> GetCorrectionMotionFiledDetails(PTXboParameters model);
        List<PTXboPanelDocketIDDetails> GetPanelDocketIDHistory(PTXboParameters model);
        List<PTXboHearingNoticeLetterHistory> GetHearingNoticeLetterDateHistory(PTXboParameters model);
        PTXboUserEnteredAofADetail getAofADetails(PTXboParameters model);
        List<PTXboHearingDetails> getHearingInfo(int Accountid);
        List<PTXboHearingDetails> getPastHearingInfo(int Accountid);
        List<PTXboPreviousAofADetails> getAofAPreviousRevisedDateHistory(int Accountid);
        List<PTXboDateCodedHistory> getDateCodedEndHistory(int Accountid);
        List<PTXboCadLegalNameHistory> getCADLegalNameHistory(int Accountid);
        DataTable getClientContactLogLitigation(PTXboParameters model);
        List<PTXboDateCodedHistory> getDateCodedHistory(int Accountid);
        PTXboArbitrationDetails GetTaxyearBasedArbitration(PTXboParameters model);
        List<PTXboArbitratorDetails> getArbitratorDetails(int Arbitrator);
        List<PTXboDocumentsFromPaperwise> getDocumentsfromPaperwiseUsingMultiDoctype(PTXboDocumentsFromPaperwise objSearchCriteria);
        DataSet LoadLitigationDetails(PTXboParameters model);
        string GetPendingLitigationTaxYear(int AccountID);
        List<PTXboLitigationDocuments> ViewDocuments(PTXboParameters model);
        List<PTXboSupplementaryDetails> LoadSupplementHistory(int LitigationID);
        List<PTXboLitigationAccountDetails> GetTrialDateHistory(PTXboParameters model);
        DataSet LoadLitigationDetailsII(PTXboParameters model);
        string GetPendingLitigationTaxYearII(PTXboParameters model);
        List<PTXboLitigationSecAccountDetails> SecGetTrialDateHistory(PTXboParameters model);
        PTXboMainScreenValues getMainScreenValues(PTXboParameters model);
        List<PTXboPropertySurveyClientInputs> getMSPropertySurvey(PTXboPropertyConditionModel objmodel);
        List<PTXboClientCreditTransaction> GetClientCreditDetails(int clientID);
        List<PTXboBPPPropertyValues> getMainScreenBPPPropertyValues(PTXboBPPPropertyValues objmodel);
        List<PTXboILHearingRemarks> GetILHearingRemarks(PTXboParameters model);
        List<PTXboILAgentRemarks> GetILAgentRemarks(PTXboParameters model);
        PTXboILHearingDetails GetILHearingDetails(PTXboParameters model);
        DataSet GetDMflag(PTXboParameters model);
        List<PTXboPOAReceivedDateHistory> getPOAReceivedDateHistory(int ClientID);
        List<PTXboILHearingRemarks> GetIOWAHearingRemarks(PTXboParameters model);
        List<PTXboILAgentRemarks> GetIOWAAgentRemarks(PTXboParameters model);
        PTXboILHearingDetails GetIOWAHearingDetails(PTXboParameters model);
        PTXboGAHearingDetails GetGAHearingDetails(PTXboParameters model);
    }
}
